#!/usr/bin/env bash
# Idempotent server bootstrap for a fresh Ubuntu 22.04/24.04 EC2 instance.
#
# Run from your laptop (after SSH-ing in):
#     curl -fsSL <raw-github-url>/infrastructure/prod/bootstrap.sh | sudo bash -s -- \
#         <DOMAIN> <LETSENCRYPT_EMAIL> <REPO_DEPLOY_KEY_B64>
#
# Or run after `git clone`-ing the repo to /opt/pgmanage:
#     sudo bash /opt/pgmanage/infrastructure/prod/bootstrap.sh <DOMAIN> <LETSENCRYPT_EMAIL>
#
# What it does:
#   1. Installs Docker + Docker Compose plugin
#   2. Creates /opt/pgmanage (clones repo if needed)
#   3. Generates strong secrets + an RS256 keypair → /etc/pgmanage/.env
#   4. Runs alembic migrations
#   5. Brings the stack up

set -euo pipefail

DOMAIN="${1:?usage: bootstrap.sh <DOMAIN> <LETSENCRYPT_EMAIL>}"
LETSENCRYPT_EMAIL="${2:?usage: bootstrap.sh <DOMAIN> <LETSENCRYPT_EMAIL>}"
REPO_URL="${REPO_URL:-https://github.com/mastanbasha11/pgmanage.git}"
REPO_DIR="${REPO_DIR:-/opt/pgmanage}"
ENV_FILE="${ENV_FILE:-/etc/pgmanage/.env}"

log()  { printf '\033[1;32m[bootstrap]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "must be run as root (use sudo)"

# ── 1. Docker & Compose ──────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release git openssl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  # Allow the default ubuntu user to run docker without sudo
  if id -u ubuntu >/dev/null 2>&1; then
    usermod -aG docker ubuntu
  fi
else
  log "Docker already installed: $(docker --version)"
fi

# ── 2. Repo ──────────────────────────────────────────────────────────────────
if [[ ! -d "$REPO_DIR/.git" ]]; then
  log "cloning $REPO_URL into $REPO_DIR"
  git clone --depth 1 "$REPO_URL" "$REPO_DIR"
else
  log "repo present at $REPO_DIR — pulling latest"
  git -C "$REPO_DIR" pull --ff-only
fi

# ── 3. Secrets / .env ────────────────────────────────────────────────────────
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

if [[ ! -f "$ENV_FILE" ]]; then
  log "generating $ENV_FILE — KEEP THIS FILE SAFE"

  POSTGRES_PASSWORD=$(openssl rand -hex 32)
  REDIS_PASSWORD=$(openssl rand -hex 32)
  SECRET_KEY=$(openssl rand -hex 32)

  # RS256 keypair
  TMP=$(mktemp -d)
  trap 'rm -rf "$TMP"' EXIT
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$TMP/jwt-private.pem" 2>/dev/null
  openssl rsa -in "$TMP/jwt-private.pem" -pubout -out "$TMP/jwt-public.pem" 2>/dev/null
  # awk-encode multi-line PEM as a single env-var line with literal \n
  jwt_priv=$(awk 'BEGIN{ORS="\\n"} {print}' "$TMP/jwt-private.pem")
  jwt_pub=$(awk  'BEGIN{ORS="\\n"} {print}' "$TMP/jwt-public.pem")

  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%FT%TZ)
DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
CORS_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}
ALLOWED_HOSTS=${DOMAIN},www.${DOMAIN}

POSTGRES_USER=pgmanage
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=pgmanage

REDIS_PASSWORD=${REDIS_PASSWORD}

SECRET_KEY=${SECRET_KEY}
RS256_PRIVATE_KEY="${jwt_priv}"
RS256_PUBLIC_KEY="${jwt_pub}"

# Optional — fill in later
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
META_APP_SECRET=
SES_FROM_EMAIL=
EOF
  chmod 600 "$ENV_FILE"
else
  log "$ENV_FILE already exists — leaving in place"
fi

# ── 4. Build & run ───────────────────────────────────────────────────────────
cd "$REPO_DIR"
log "building containers (first time can take ~5 min on t3.medium)"
docker compose --env-file "$ENV_FILE" -f docker-compose.prod.yml build

log "running database migrations"
docker compose --env-file "$ENV_FILE" -f docker-compose.prod.yml --profile migrate run --rm migrate

log "starting stack"
docker compose --env-file "$ENV_FILE" -f docker-compose.prod.yml up -d

# ── 5. Health gate ───────────────────────────────────────────────────────────
log "waiting for backend health (up to 90s)"
for _ in $(seq 1 18); do
  sleep 5
  if docker compose --env-file "$ENV_FILE" -f docker-compose.prod.yml exec -T backend \
      python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://localhost:8000/health").status==200 else 1)' \
      >/dev/null 2>&1; then
    log "backend is healthy"
    break
  fi
done

log "Bootstrap complete."
log "Caddy will fetch a Let's Encrypt cert as soon as DNS for ${DOMAIN} resolves to this host."
log "Tail logs with:  docker compose --env-file ${ENV_FILE} -f ${REPO_DIR}/docker-compose.prod.yml logs -f"
