from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import (
    Boolean, Date, DateTime, Enum as PgEnum, ForeignKey,
    Index, Integer, String, Text, UniqueConstraint, func,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Payment(Base):
    __tablename__ = "payments"
    __table_args__ = (
        UniqueConstraint("idempotency_key", name="uq_payment_idempotency"),
        Index("ix_payments_property_month_year", "property_id", "for_year", "for_month"),
        Index("ix_payments_tenant_created", "tenant_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False, index=True)
    property_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False, index=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True
    )

    # Amount in paise — NEVER float
    amount_paise: Mapped[int] = mapped_column(Integer, nullable=False)

    payment_type: Mapped[str] = mapped_column(
        PgEnum(
            "RENT", "ADVANCE", "DEPOSIT", "FOOD", "OTHER_CHARGE", "REFUND",
            name="payment_type_enum",
            create_type=False,
        ),
        nullable=False,
    )
    payment_mode: Mapped[str] = mapped_column(
        PgEnum(
            "CASH", "UPI", "BANK_TRANSFER", "CARD", "CHEQUE",
            name="payment_mode_enum",
            create_type=False,
        ),
        nullable=False,
        default="CASH",
    )

    reference_number: Mapped[str | None] = mapped_column(String(200), nullable=True)
    upi_id: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Which rent period this payment covers
    for_month: Mapped[int | None] = mapped_column(Integer, nullable=True)
    for_year: Mapped[int | None] = mapped_column(Integer, nullable=True)

    collected_by: Mapped[uuid.UUID | None] = mapped_column(PGUUID(as_uuid=True), nullable=True)
    collected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    receipt_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    receipt_s3_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Idempotency: prevents double-recording on network retry
    idempotency_key: Mapped[str | None] = mapped_column(String(100), nullable=True)

    is_deleted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    deleted_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class RentLedgerEntry(Base):
    """
    One row per tenant per month. Generated by cron on 1st of each month.
    Tracks: how much was due vs how much was paid.
    """
    __tablename__ = "rent_ledger_entries"
    __table_args__ = (
        UniqueConstraint("tenant_id", "month", "year", name="uq_ledger_tenant_month_year"),
        Index("ix_ledger_property_period", "property_id", "year", "month"),
        Index("ix_ledger_status", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True
    )
    property_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False, index=True)

    month: Mapped[int] = mapped_column(Integer, nullable=False)   # 1-12
    year: Mapped[int] = mapped_column(Integer, nullable=False)

    amount_due_paise: Mapped[int] = mapped_column(Integer, nullable=False)
    amount_paid_paise: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    status: Mapped[str] = mapped_column(
        PgEnum(
            "PAID", "PARTIAL", "UNPAID", "WAIVED",
            name="rent_status_enum",
            create_type=False,
        ),
        nullable=False,
        default="UNPAID",
        index=True,
    )

    due_date: Mapped[date] = mapped_column(Date, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    @property
    def outstanding_paise(self) -> int:
        return max(0, self.amount_due_paise - self.amount_paid_paise)
